// Translation strings for English
const en = {
  // Common
  home: 'Home',
  back: 'Back',
  next: 'Next',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  add: 'Add',
  loading: 'Loading...',
  error: 'Error',
  success: 'Success',
  warning: 'Warning',
  
  // Home Screen
  homeTitle: 'AarogyaMitra',
  homeSubtitle: 'Your Health Companion',
  tapAny: 'Tap on any vital to record or view history',
  
  // Navigation
  symptoms: 'Symptoms',
  startChat: 'Start a chat and get safe guidance',
  appointments: 'My Appointments',
  upcomingPast: 'Upcoming, past, and new bookings',
  reminders: 'Reminders',
  medicinesFollowUp: 'Medicines and follow-up appointments',
  medicalDocs: 'Medical Documents',
  uploadView: 'Upload and view prescriptions/tests',
  familyProfiles: 'Family Profiles',
  manageSwitchFamily: 'Manage and switch between family members',
  recordVitals: 'Record Vitals',
  recordBPSugarSpO2: 'Record your blood pressure, sugar, SpO2',
  help: 'Help',
  profile: 'Profile',
  settings: 'Settings',
  
  // Vitals
  recordReading: 'Record Reading',
  history: 'History',
  bloodPressure: 'Blood Pressure',
  bloodSugar: 'Blood Sugar',
  spO2: 'SpO2',
  temperature: 'Temperature',
  heartRate: 'Heart Rate',
  weight: 'Weight',
  saveReading: 'Save Reading',
  lastRecording: 'Last',
  noReadings: 'No readings recorded yet',
  systolic: 'Systolic',
  diastolic: 'Diastolic',
  mmHg: 'mmHg',
  level: 'Level',
  mgdL: 'mg/dL',
  percentage: '%',
  fasting: 'Fasting',
  postMeal: 'Post-Meal',
  BPM: 'BPM',
  celsius: '°C',
  fahrenheit: '°F',
  kg: 'kg',
  lbs: 'lbs',
  abnormalReading: 'Abnormal reading',
  criticalReading: 'Critical reading',
  
  // Vitals Thresholds
  highBP: 'High blood pressure',
  lowBP: 'Low blood pressure',
  hypertensiveCrisis: 'Hypertensive crisis — seek immediate care',
  highGlucose: 'High fasting glucose',
  lowGlucose: 'Low blood sugar',
  highPostMeal: 'High post-meal glucose',
  lowSpO2: 'Low SpO2',
  veryLowSpO2: 'Very low SpO2',
  fever: 'Fever',
  veryHighTemp: 'Very high temperature',
  lowTemp: 'Low body temperature',
  highHR: 'High heart rate',
  veryHighHR: 'Very high heart rate',
  lowHR: 'Low heart rate',
  unknownTime: 'Unknown time',
  
  // Documents
  uploadDocument: 'Upload Document',
  medicineReceipt: 'Medicine Receipt/Prescription',
  labTest: 'Lab Test Report',
  previewNotAvailable: 'Preview not available',
  documentUploadQueued: 'Document queued. It will upload automatically when you are back online.',
  
  // Appointments
  bookNewAppointment: 'Book new appointment',
  upcoming: 'Upcoming',
  past: 'Past',
  noAppointments: 'No appointments',
  
  // Reminders
  addReminder: 'Add reminder',
  medicines: 'Medicines',
  followUps: 'Follow-ups',
  
  // Language
  language: 'Language',
  selectLanguage: 'Select Language',
  english: 'English',
  hindi: 'हिंदी',
  tamil: 'தமிழ்',
  telugu: 'తెలుగు',
  kannada: 'ಕನ್ನಡ',
  malayalam: 'മലയാളം',
  marathi: 'मराठी',
  
  // Profiles
  active: 'Active',
  addFamilyMember: 'Add Family Member',
  currentlyActive: 'Currently Active',
  manageSwitchFamily: 'Manage and switch between family members',
  
  // Symptom Checker
  aiSymptomChecker: 'AI Symptom Checker',
  typeSymptoms: 'Type your symptoms...',
  aarogyaMitraGreeting: 'Hi, I am AarogyaMitra. How can I help you today? Please tell me about your symptoms.',
  chooseFromGallery: 'Choose from gallery',
  takeAPhoto: 'Take a photo',
  attachImage: 'Attach image',
  chooseAnOption: 'Choose an option',
  imageError: 'Image error',
  unableToReadImage: 'Unable to read that image. Please try another.',
  couldNotPickImage: 'Could not pick an image. Please try again.',
  couldNotCaptureImage: 'Could not capture an image. Please try again.',
  cameraError: 'Camera error',
  permissionNeeded: 'Permission needed',
  allowPhotoAccess: 'Please allow photo access to attach images.',
  allowCameraAccess: 'Please allow camera access to take photos.',
  
  // Reminders
  addReminder: 'Add reminder',
  medicines: 'Medicines',
  followUps: 'Follow-ups',
  tapAddReminder: 'Tap "Add reminder" to create your first one.',
  myReminders: 'My Reminders',
  unnamedMedicine: 'Unnamed medicine',
  appointment: 'Appointment',
  reminderSaveFailed: 'Could not save the reminder. Please try again.',
  reminderUpdatedSuccessfully: 'Reminder updated successfully!',
  reminderUpdateQueued: 'Reminder update queued. It will sync when you are back online.',
  reminderAddedSuccessfully: 'Reminder added successfully!',
  reminderQueued: 'Reminder queued. It will sync when you are back online.',
  reminderDeletedSuccessfully: 'Reminder deleted successfully!',
  reminderDeleteQueued: 'Reminder delete queued. It will finish when you are back online.',
  reminderDeleteFailed: 'Could not delete the reminder. Please try again.',
  reminderPendingSync: 'Waiting to sync…',
  reminderUpdatePendingSync: 'Changes waiting to sync…',
  queuedReminderNotEditable: 'This reminder is waiting to sync. Please try editing once you are back online.',
  
  // Appointments
  upcoming: 'Upcoming',
  past: 'Past',
  noAppointmentsYet: 'No appointments yet',
  bookNewAppointment: 'Book a new appointment to see it listed here.',
  loginToSeeAppointments: 'Log in to see upcoming visits and start video calls with your doctors.',
  myAppointments: 'My Appointments',
  joinCall: 'Join Call',
  bookNewAppointmentButton: 'Book new appointment',
  noScheduleSet: 'No schedule set',
  meetingLinkNotAvailableAppointment: 'Meeting link not available for this appointment.',
  unableToOpenVideoCallAppointment: 'Unable to open the video call. Please try again.',
  unableToLoadAppointments: 'Unable to load appointments at the moment. Please try again later.',
  doctor: 'Doctor',
  specialty: 'Specialty',
  signInToTrackAppointments: 'Sign in to track appointments',
  
  // Book Appointment
  bookAppointment: 'Book Appointment',
  editAppointment: 'Edit Appointment',
  selectSpecialty: 'Select Specialty',
  selectDate: 'Select Date',
  selectTime: 'Select Time',
  doctorName: 'Doctor Name',
  notes: 'Notes',
  confirmBooking: 'Confirm Booking',
  loadingAppointment: 'Loading appointment...',
  pleaseSignInToBook: 'Please sign in to book an appointment.',
  pleaseCompleteAllFields: 'Please complete all required fields.',
  invalidDateOrTime: 'The selected date or time is invalid.',
  chooseFutureTime: 'Please choose a future time for your appointment.',
  appointmentUpdatedSuccessfully: 'Appointment updated successfully.',
  appointmentQueued: 'Appointment queued. It will sync when you are back online.',
  appointmentUpdateQueued: 'Appointment update queued. It will sync when you are back online.',
  couldNotLoadAppointment: 'Could not load the appointment. Please try again later.',
  couldNotBookAppointment: 'Could not book the appointment. Please try again.',
  appointmentPendingSync: 'Waiting to sync…',
  appointmentUpdatePendingSync: 'Changes waiting to sync…',
  queuedAppointmentNotEditable: 'This appointment is waiting to sync. Please try editing after it uploads.',
  queuedJoinDisabled: 'Join link will be available once this appointment syncs online.',
  
  // Booking Confirmed
  bookingConfirmed: 'Booking Confirmed',
  bookingConfirmedMessage: 'Your appointment is set with {doctorName}.',
  assigned: 'Assigned',
  pendingSchedule: 'Pending schedule',
  joinVideoCall: 'Join Video Call',
  addToReminder: 'Add to Reminder',
  backToAppointments: 'Back to Appointments',
  meetingLinkNotAvailable: 'Meeting link is not available for this appointment.',
  unableToOpenVideoCall: 'Unable to open the video call. Please try again from My Appointments.',
  
  // Document Upload
  uploadOptions: 'Upload Options',
  uploadFromGallery: 'Upload from Gallery',
  scanOrCapture: 'Scan or Capture',
  watchVideoToUnderstand: 'Watch video to understand how to upload',
  watchVideoMessage: 'This would open a video player showing the user how to take a clear photo of their medical documents.',
  cameraRollPermissionDenied: 'Sorry, we need camera roll permissions to make this work!',
  cameraPermissionDenied: 'Sorry, we need camera permissions to make this work!',
  
  // Document Preview
  preview: 'Preview',
  pleaseSignInToUploadDocs: 'Please sign in to upload documents.',
  documentNotAvailable: 'Document not available. Please try uploading again.',
  pleaseEnterDocumentName: 'Please enter a name for this document.',
  pleaseConfirmDocumentClear: 'Please confirm your document is clear and readable.',
  documentName: 'Document Name',
  addTitleToFindLater: 'Add a title so you can find this later',
  confirmDocumentUpload: 'Confirm Document Upload',
  imageTooLargeAfterCompression: 'Image is too large even after compression. Please try a smaller image or take a clearer close-up photo.',
  imageTooLargeAfterCompression2: 'Image is still too large after compression. Please select a smaller image.',
  permissionDeniedToUploadDocs: 'You do not have permission to upload documents. Please check your account.',
  couldNotUploadDocument: 'Could not upload the document. Please try again.',
  documentUploadedSuccessfully: 'Document uploaded successfully!',
  previewNotAvailable: 'Preview not available',
  
  // Documents List
  medicalDocuments: 'Medical Documents',
  uploadDocument: 'Upload Document',
  queuedLabel: 'Queued',
  documentPendingSync: 'Waiting to upload…',
  noDocumentsYet: 'No documents yet',
  uploadPrescriptionsLabReports: 'Upload prescriptions, lab reports, or discharge summaries so they are easy to find.',
  dateUnavailable: 'Date unavailable',
  untitledDocument: 'Untitled document',
  pdfViewerNotImplemented: 'PDF viewer not yet implemented. You can still download the file using your device.',
  documentFormatNotSupported: 'Document format not yet supported for preview.',
  unableToLoadDocuments: 'Unable to load documents right now. Please try again later.',
  
  // Emergency
  emergencyAlertActive: 'Emergency Alert Active',
  alertCancelled: 'Alert Cancelled',
  alertingNearestAmbulance: 'Alerting nearest ambulance and sending your location...',
  ambulanceDispatched: 'Ambulance has been dispatched. Showing location on map for better coordination...',
  emergencyAlertCancelled: 'Emergency alert cancelled.',
  clickHereToStop: 'Click here to stop',
  liveMapTracking: 'Live map tracking would appear here.',
  locating: 'Locating...',

  // AI Chat Screen
  aiChat: 'AI Assistant',
  aiChatWelcome: 'Namaste! I\'m AarogyaMitra, your health companion. I\'m here to help you with your health in a simple way.',
  aiHeroSubtitle: 'Your all-in-one health companion for symptoms, doctors & reminders',
  aiHeroDescribeSymptoms: 'Describe symptoms',
  aiHeroBookDoctors: 'Book doctors',
  aiHeroSetReminders: 'Set reminders',
  aiHeroChatNow: 'Chat now',
  whatCanIHelpYouWith: 'What would you like to do today?',
  notFeelingWell: 'I\'m not feeling well',
  recordMyVitals: 'Record my vitals',
  bookAppointment: 'Book an appointment',
  tellMeAboutSymptoms: 'Tell me more about what\'s bothering you. Which one applies to you?',
  fever: 'I have fever',
  cough: 'I have cough',
  bodyPain: 'Body pain',
  otherSymptom: 'Other symptoms',
  whichVitalToRecord: 'Which vital would you like to record?',
  chooseSpecialty: 'Which type of doctor do you need?',
  generalCheckup: 'General Checkup',
  cardiology: 'Heart Specialist',
  neurology: 'Brain Specialist',
  dermatology: 'Skin Specialist',
  whatElseCanIHelp: 'What else can I help you with?',
  backToMenu: 'Back to Menu',
  continueChat: 'Continue Chat',
  selfCare: 'Self-care tips',
  bookAppointmentForSymptom: 'Book appointment',
  proceedToRecord: 'Proceed to Record',
  proceedToBook: 'Proceed to Book',
  recordingVitalBp: 'Great! Let\'s record your blood pressure.',
  recordingVitalSugar: 'Great! Let\'s record your blood sugar.',
  recordingVitalTemp: 'Great! Let\'s record your temperature.',
  recordingVitalHr: 'Great! Let\'s record your heart rate.',
  bookingWithGeneral: 'I\'ll help you book a general checkup appointment.',
  bookingWithCardio: 'I\'ll help you book an appointment with a heart specialist.',
  bookingWithNeuro: 'I\'ll help you book an appointment with a brain specialist.',
  bookingWithDerm: 'I\'ll help you book an appointment with a skin specialist.',
  symptomSelectedFever: 'I understand you have fever. Have you measured your temperature?',
  symptomSelectedCough: 'I understand you have a cough. When did it start?',
  symptomSelectedPain: 'I\'m sorry to hear you have body pain. Which area of your body hurts?',
  symptomSelectedOther: 'Please tell me more about your symptoms.',
  recommendationForFever: 'For fever, make sure to drink plenty of water and rest well. If it continues, please see a doctor.',
  recommendationForCough: 'For a cough, drink warm water with honey or ginger. If it doesn\'t improve in a few days, consult a doctor.',
  recommendationForPain: 'Try to rest the affected area and apply a warm compress. If the pain persists, please see a doctor.',
  recommendationForOther: 'Would you like to book an appointment to discuss your symptoms with a doctor?',
  errorProcessingRequest: 'Sorry, I had trouble understanding that. Please try again.',
  thinking: 'Thinking...',
  typeMessage: 'Type a message',

  // AI Chat - New Conversational Flow
  describeSymptomsInDetail: 'Please tell me about your symptoms in detail. What are you experiencing?',
  whichVitalToRecordChat: 'Which vital would you like to record?',
  recordingVitalBP: 'Let\'s record your blood pressure.',
  recordingVitalSUGAR: 'Let\'s record your blood sugar.',
  recordingVitalTEMP: 'Let\'s record your temperature.',
  recordingVitalHR: 'Let\'s record your heart rate.',
  recordingVitalWEIGHT: 'Let\'s record your weight.',
  proceedToRecordQuestion: 'Are you ready to record this measurement?',
  appointmentQuestion: 'Do you already have a doctor in mind, or would you like us to suggest one?',
  haveDoctor: 'I have a doctor',
  needSuggestion: 'Suggest a doctor',
  describeProblem: 'Please briefly describe what health problem you\'d like to consult about.',
  chooseSpecialtyChat: 'Based on your concern, which type of specialist would you need?',
  proceedToBookQuestion: 'Shall we proceed to book the appointment?',
  seriousSymptomWarning: 'Your symptoms sound serious. If you feel worse, please visit a clinic or emergency center immediately.',
  noDoctorSelected: 'I do not have a doctor selected yet. Could you describe your symptoms once more?',
  findingSlotWithDoctor: 'Great! Let\'s find a slot with {doctorName}. Tap the calendar card below to choose a date.',
  reminderType: 'What type of reminder would you like to set?',
  medicineReminder: 'Medicine Reminder',
  appointmentReminder: 'Appointment Reminder',
  tabletName: 'Please tell me the name of the tablet/medicine.',
  tabletDosage: 'How many tablets do you need to take?',
  tabletFrequency: 'How often should you take this medicine? (e.g., Once daily, Twice daily, As needed)',
  tabletTime: 'Would you like me to set a time to remind you?',
  doctorName: 'What is the name of your doctor?',
  appointmentDate: 'When is your appointment? (e.g., 15 November 2024)',
  appointmentTime: 'What time is your appointment? (e.g., 2:30 PM)',
  reminderSetSuccessfully: 'Great! Your reminder has been set successfully.',
  addAnother: 'Add another reminder',
  documentUploadQuestion: 'You can upload medical documents like prescriptions, lab reports, and discharge summaries. Would you like to upload a document now?',
  medicalDocuments: 'Medical Documents',
  addReminder: 'Add Reminder',
  typeYourMessage: 'Type your message...',
  yes: 'Yes',
  no: 'No',
  doctorSuggestionPrompt: 'Did you mean one of these doctors?',
  reenterName: 'Re-enter name',
  keepDoctorName: 'Keep "{doctorName}"',
  appointmentDatePrompt: 'Tap the calendar card below to pick your appointment date.',
  continueWithDoctor: "Okay, I'll continue with {doctorName}.",
  medicineNamePrompt: 'What is the name of the medicine or tablet? (If you don\'t know the name, just say "I don\'t know" and I can help you identify it by color and what it\'s for!)',
  chooseDateFirst: 'Please choose a date first using the calendar card.',
  provideMedicineBeforeReminder: 'Please share the medicine name and dosage before setting a reminder time.',
  dateAlreadyPassed: 'That date has already passed. Please pick another day.',
  doctorOptionNotFound: 'I could not find that doctor option. Please type the name again.',
  checkingDoctorDirectory: 'Give me a moment while I check that doctor in our directory...',
  appointmentAlreadyScheduled: 'Your appointment is already scheduled. Please use the buttons above to continue.',
  reminderReady: 'Your reminder is ready. Please use the quick buttons above to continue.',
  doctorSuggestionMissing: 'I could not find a doctor to suggest yet. Please try describing your symptoms again.',
  doctorSuggestionSummary: 'I have shared the top doctors I could find. Would you like to book with the last doctor I mentioned or describe your symptoms again?',
  describeSymptomsPrompt: 'No problem. Tell me what symptoms you have and I will suggest a doctor.',
  symptomDescriptionShortPrompt: 'Please share a few words about your symptoms so I can help.',
  chooseSpecialtyPrompt: 'I could not find a matching doctor automatically. Please choose a specialty to continue.',
  bookOrAnotherPrompt: 'Would you like to book with this doctor or see another option? You can also tap the buttons above.',
  useCardsHint: 'Please use the cards above to pick the appointment date or time, or type them in.',
  needAnythingElse: 'Need anything else?',
  visitClinicSoon: 'Please visit the nearest clinic or call your doctor. I will add a direct booking option soon.',
  selfCareOrMenu: 'Would you like the self-care tips again or go back to the menu?',
  pickNewTime: 'No problem. Pick a new time using the clock card or type it again.',
  dateAlreadyPassedDetailed: 'That date has already passed. Please enter a future date (for example: 15 Nov or 15-11-2025).',
  askAppointmentTime: 'What time is your appointment? Use the clock below or type it (e.g., 10:30 AM or 14:30).',
  doctorNameNoMatch: "I couldn't find a close match. Please type the doctor's name again.",
  typeDoctorNameAgain: "No problem. Please type the doctor's name again.",
  askDoctorNameThanks: "Thanks for sharing. What's the doctor's name?",
  askDoctorNameContinue: "Please share the doctor's name so I can continue.",
  doctorSuggestionSymptomIntro: 'I couldn\'t find "{doctorName}". Based on {summary}, here are some {specialty} doctors you can pick instead:',
  doctorNameFallback: 'I couldn\'t find "{doctorName}" in my doctor list, but I\'ll still schedule with that name.',
  yourConcern: 'your concern',
  reenterDatePrompt: 'Please enter the date again. You can use formats like:\n• 15 Nov\n• 15-11-2025\n• Nov 15\n• November 15, 2025',
  needDateBeforeTime: 'I need the appointment date before we can set the time. Please share it again.',
  reenterAppointmentTime: 'Please pick the appointment time again using the clock or type it out.',
  apiKeyMissing: 'Gemini API key is missing. Please configure it in app.json > extra.geminiApiKey.',
  selfCarePlanOrDoctor: 'Would you like a self-care plan or contact a doctor?',
  symptomNetworkIssue: 'I ran into an issue. Please check your internet connection and try describing your symptoms again.',
  tabletColorPrompt: 'No problem! Let me help you. What color is the tablet? (e.g., white, red, blue, yellow, etc.)',
  medicineNameClarification: "I'm not sure what you meant. Could you please tell me the name of the medicine, or let me know if you don't know it?",
  tabletPurposePrompt: 'Good! Now, what is this medicine for? (e.g., for heart, for blood pressure, for headache, for fever, etc.)',
  tabletColorClarification: 'Can you describe the color? Like white, red, blue, yellow, green, orange, pink, brown, black, etc.?',
  tabletUsageClarification: 'What is this medicine used for? (e.g., for blood pressure, for pain, for heart, for diabetes, for fever, etc.)',
  tabletReminderTimePrompt: 'What time should I remind you? Use the clock card below to pick an exact time.',
  estimateDosagePrompt: 'No problem! Can you give me an estimate? Like "1 tablet", "half a tablet", or "2 tablets"?',
  dosageClarificationPrompt: 'I didn\'t quite understand the dosage. Please tell me something like "1 tablet", "half", "2 tablets", etc.',
  medicineTimeParseHint: 'I didn\'t quite understand "{userInput}". Please tap the clock above or enter the time as:\n• 14:30 (24-hour)\n• 2:30 PM (12-hour)\n• 14 30 (with space)\n• 2 30 pm (with space)',
  dateParseHint: 'I didn\'t quite understand "{userInput}". Please enter the date as:\n• 15 Nov\n• 15-11-2025\n• Nov 15\n• November 15, 2025',
  timeParseHint: 'I didn\'t quite understand "{userInput}". You can tap the clock above or enter the time as:\n• 14:30 (24-hour)\n• 2:30 PM (12-hour)\n• 14 30 (with space)\n• 2 30 pm (with space)',
  clockPickerSubtitleDefault: 'Tap the hour and minute you prefer.',
  pickReminderTimeTitle: 'Pick a reminder time',
  reminderTimeSubtitle: 'Tap an hour, then a minute. Reminders repeat daily at the time you choose.',
  bookAnotherAppointment: 'Book another appointment',
  confirmParsedTime: 'Did you mean {value}? Is that correct?',
  reviewAttachedImage: 'Please review the attached image.',
  genericDoctorName: 'Doctor',
  acceptingNewPatients: 'Accepting new patients',
  currentlyWaitlisted: 'Currently waitlisted (I can still request a slot)',
  symptomUnderstanding: 'Here is what I understood: {summary}',
  thanksForDetails: 'Thanks for sharing those details!',
  bestSpecialtyFit: 'Based on this, a {specialty} would be the best fit.',
  doctorExperienceLabel: 'Experience: {years}+ yrs',
  doctorLanguagesLabel: 'Languages: {languages}',
  doctorStatusLabel: 'Status: {status}',
  bookWithThisDoctor: 'Book with this doctor',
  showAnotherDoctor: 'Show another doctor',
  bookPreviousDoctor: 'Book previous doctor',
  describeSymptomsAgain: 'Describe symptoms again',
  medicineReminderConfirmation: "Great! I've set a daily reminder for {medicineName} at {time}. You'll receive reminders every day at that time.",
  appointmentReminderConfirmation: "Perfect! I've set a reminder and added your appointment with {doctorName} on {date} at {time} to the My Appointments tab.",
  escalateToDoctor: 'Escalate to Doctor',
  selfCarePlan: 'Self Care Plan',
  selfCarePlanIntro: 'Here is a simple self-care plan:',
  selfCareTip1: 'Drink 8-10 glasses of water unless advised otherwise.',
  selfCareTip2: 'Eat light, home-cooked meals like khichdi or soups.',
  selfCareTip3: 'Sleep 7-8 hours and avoid excessive screen time.',
  selfCareTip4: 'Avoid self-medicating; stick to medicines already prescribed.',
  selfCareTip5: 'If symptoms worsen or new ones appear, consult a doctor immediately.',
  
  // Medical Documents Chat
  takingToUploadScreen: 'Taking you to upload your medical document now...',
  continueToUpload: 'Continue to Upload',
  documentUploadSkipped: 'No problem! You can upload medical documents anytime you need to. Just head to the Medical Documents section.',
  
  // AI Chat - Vital Recording Instructions
  bpInstructions: 'To record your blood pressure, you\'ll need a blood pressure machine (digital or manual). Please measure your blood pressure and provide two readings: Systolic (top number) and Diastolic (bottom number). For example: 120 80 or 120/80. Please enter your readings now.',
  sugarInstructions: 'To record your blood sugar, you\'ll need a glucose meter. Please prick your finger gently and use the meter to measure your blood sugar level. Enter the reading in mg/dL. For example: 120. Please enter your reading now.',
  tempInstructions: 'To record your temperature, you\'ll need a thermometer (digital, infrared, or mercury). Place it under your arm or mouth as instructed and measure your body temperature. Enter the reading in Fahrenheit. For example: 98.6. Please enter your reading now.',
  hrInstructions: 'To record your heart rate, you can either count your pulse manually or use a device. Take your pulse for one full minute. Enter your heart rate in beats per minute (bpm). For example: 72. Please enter your reading now.',
  weightInstructions: 'To record your weight, please stand on a weighing scale in the morning before breakfast if possible. Enter your weight in kilograms. For example: 70. Please enter your reading now.',
  spo2Instructions: 'To record your SpO2 (oxygen saturation), you\'ll need a pulse oximeter. Place it on your finger and wait for the reading. Enter your SpO2 percentage. For example: 98. Please enter your reading now.',
  
  // Vital validation error messages
  bpFormatError: 'Please provide two readings for blood pressure (Systolic and Diastolic). Use format: 120 80 or 120/80',
  bpRangeError: 'Blood pressure values seem out of range. Normal range: Systolic 60-250, Diastolic 30-150. Please check and try again.',
  sugarFormatError: 'Please enter a single blood sugar reading. Use format: 120',
  sugarRangeError: 'Blood sugar value seems out of range. Normal range: 50-500 mg/dL. Please check and try again.',
  tempFormatError: 'Please enter a single temperature reading. Use format: 98.6',
  tempRangeError: 'Temperature value seems out of range. Normal range: 95-105°F. Please check and try again.',
  hrFormatError: 'Please enter a single heart rate reading. Use format: 72',
  hrRangeError: 'Heart rate value seems out of range. Normal range: 40-200 bpm. Please check and try again.',
  weightFormatError: 'Please enter a single weight reading. Use format: 70',
  weightRangeError: 'Weight value seems out of range. Normal range: 10-250 kg. Please check and try again.',
  spo2FormatError: 'Please enter a single SpO2 reading. Use format: 98',
  spo2RangeError: 'SpO2 value seems out of range. Normal range: 70-100%. Please check and try again.',
  vitalSavedSuccessfully: 'Great! Your reading has been recorded successfully.',
  recordAnother: 'Record Another',
  tryAgain: 'Try Again',
  errorSavingVital: 'There was an error saving your vital. Please try again.',
};

export default en;
