// Translation strings for Hindi (हिंदी)
const hi = {
  // Common
  home: 'होम',
  back: 'वापस',
  next: 'आगे',
  save: 'सहेजें',
  cancel: 'रद्द करें',
  delete: 'हटाएं',
  edit: 'संपादित करें',
  add: 'जोड़ें',
  loading: 'लोड हो रहा है...',
  error: 'त्रुटि',
  success: 'सफल',
  warning: 'चेतावनी',
  
  // Home Screen
  homeTitle: 'आरोग्यमित्र',
  homeSubtitle: 'आपका स्वास्थ्य साथी',
  tapAny: 'किसी भी लक्षण पर टैप करें या इतिहास देखें',
  
  // Navigation
  symptoms: 'लक्षण',
  startChat: 'चैट शुरू करें और सुरक्षित मार्गदर्शन प्राप्त करें',
  appointments: 'मेरी नियुक्तियां',
  upcomingPast: 'आने वाली, पिछली और नई बुकिंग',
  reminders: 'अनुस्मारक',
  medicinesFollowUp: 'दवाएं और फॉलो-अप नियुक्तियां',
  medicalDocs: 'चिकित्सा दस्तावेज़',
  uploadView: 'प्रिस्क्रिप्शन/परीक्षण अपलोड करें और देखें',
  familyProfiles: 'पारिवारिक प्रोफाइल',
  manageSwitchFamily: 'परिवार के सदस्यों के बीच प्रबंधन और स्विच करें',
  recordVitals: 'महत्वपूर्ण संकेत रिकॉर्ड करें',
  recordBPSugarSpO2: 'रक्तचाप, शुगर, SpO2 रिकॉर्ड करें',
  help: 'मदद',
  profile: 'प्रोफाइल',
  settings: 'सेटिंग्स',
  
  // Vitals
  recordReading: 'रीडिंग रिकॉर्ड करें',
  history: 'इतिहास',
  bloodPressure: 'रक्तचाप',
  bloodSugar: 'रक्त शर्करा',
  spO2: 'SpO2',
  temperature: 'तापमान',
  heartRate: 'दिल की दर',
  weight: 'वजन',
  saveReading: 'रीडिंग सहेजें',
  lastRecording: 'अंतिम',
  noReadings: 'अभी तक कोई रीडिंग रिकॉर्ड नहीं की गई है',
  systolic: 'सिस्टोलिक',
  diastolic: 'डायास्टोलिक',
  mmHg: 'mmHg',
  level: 'स्तर',
  mgdL: 'mg/dL',
  percentage: '%',
  fasting: 'खाली पेट',
  postMeal: 'भोजन के बाद',
  BPM: 'BPM',
  celsius: '°C',
  fahrenheit: '°F',
  kg: 'किग्रा',
  lbs: 'पाउंड',
  abnormalReading: 'असामान्य रीडिंग',
  criticalReading: 'गंभीर रीडिंग',
  
  // Vitals Thresholds
  highBP: 'उच्च रक्तचाप',
  lowBP: 'निम्न रक्तचाप',
  hypertensiveCrisis: 'उच्च रक्तचाप संकट — तुरंत मदद लें',
  highGlucose: 'उच्च रक्त शर्करा',
  lowGlucose: 'निम्न रक्त शर्करा',
  highPostMeal: 'भोजन के बाद उच्च रक्त शर्करा',
  lowSpO2: 'कम SpO2',
  veryLowSpO2: 'बहुत कम SpO2',
  fever: 'बुखार',
  veryHighTemp: 'बहुत अधिक तापमान',
  lowTemp: 'निम्न शरीर तापमान',
  highHR: 'उच्च हृदय गति',
  veryHighHR: 'बहुत अधिक हृदय गति',
  lowHR: 'निम्न हृदय गति',
  unknownTime: 'अज्ञात समय',
  
  // Documents
  uploadDocument: 'दस्तावेज़ अपलोड करें',
  medicineReceipt: 'दवा रसीद/प्रिस्क्रिप्शन',
  labTest: 'प्रयोगशाला परीक्षण रिपोर्ट',
  previewNotAvailable: 'पूर्वावलोकन उपलब्ध नहीं है',
  
  // Appointments
  bookNewAppointment: 'नई नियुक्ति बुक करें',
  upcoming: 'आने वाली',
  past: 'पिछली',
  noAppointments: 'कोई नियुक्तियां नहीं',
  
  // Reminders
  addReminder: 'अनुस्मारक जोड़ें',
  medicines: 'दवाएं',
  followUps: 'फॉलो-अप',
  
  // Language
  language: 'भाषा',
  selectLanguage: 'भाषा चुनें',
  english: 'English',
  hindi: 'हिंदी',
  tamil: 'தமிழ்',
  telugu: 'తెలుగు',
  kannada: 'ಕನ್ನಡ',
  malayalam: 'മലയാളം',
  marathi: 'मराठी',
  
  // Profiles
  active: 'सक्रिय',
  addFamilyMember: 'परिवार के सदस्य को जोड़ें',
  currentlyActive: 'वर्तमान में सक्रिय',
  manageSwitchFamily: 'परिवार के सदस्यों को प्रबंधित और स्विच करें',
  
  // Symptom Checker
  aiSymptomChecker: 'AI लक्षण जांच',
  typeSymptoms: 'अपने लक्षणों को टाइप करें...',
  aarogyaMitraGreeting: 'नमस्ते, मैं आरोग्यमित्र हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ? कृपया मुझे अपने लक्षणों के बारे में बताएं।',
  chooseFromGallery: 'गैलरी से चुनें',
  takeAPhoto: 'फोटो लें',
  attachImage: 'चित्र संलग्न करें',
  chooseAnOption: 'एक विकल्प चुनें',
  imageError: 'चित्र त्रुटि',
  unableToReadImage: 'वह चित्र पढ़ा नहीं जा सका। कृपया दूसरा प्रयास करें।',
  couldNotPickImage: 'चित्र नहीं चुना जा सका। कृपया पुनः प्रयास करें।',
  couldNotCaptureImage: 'चित्र कैप्चर नहीं किया जा सका। कृपया पुनः प्रयास करें।',
  cameraError: 'कैमरा त्रुटि',
  permissionNeeded: 'अनुमति आवश्यक है',
  allowPhotoAccess: 'चित्र संलग्न करने के लिए कृपया फोटो एक्सेस की अनुमति दें।',
  allowCameraAccess: 'फोटो लेने के लिए कृपया कैमरा एक्सेस की अनुमति दें।',
  
  // Reminders
  addReminder: 'अनुस्मारक जोड़ें',
  medicines: 'दवाइयाँ',
  followUps: 'अनुवर्ती',
  tapAddReminder: '"अनुस्मारक जोड़ें" पर टैप करके अपना पहला अनुस्मारक बनाएं।',
  myReminders: 'मेरे अनुस्मारक',
  unnamedMedicine: 'नाम रहित दवा',
  appointment: 'नियुक्ति',
  reminderSaveFailed: 'अनुस्मारक सहेजा नहीं जा सका। कृपया पुनः प्रयास करें।',
  reminderUpdatedSuccessfully: 'अनुस्मारक सफलतापूर्वक अपडेट किया गया!',
  reminderUpdateQueued: 'अनुस्मारक अपडेट कतार में है। ऑनलाइन होते ही यह सिंक हो जाएगा।',
  reminderAddedSuccessfully: 'अनुस्मारक सफलतापूर्वक जोड़ा गया!',
  reminderQueued: 'अनुस्मारक कतार में जोड़ दिया गया है। ऑनलाइन होते ही यह सिंक होगा।',
  reminderDeletedSuccessfully: 'अनुस्मारक सफलतापूर्वक हटाया गया!',
  reminderDeleteQueued: 'अनुस्मारक हटाने का अनुरोध कतार में है। ऑनलाइन होते ही यह पूरा होगा।',
  reminderDeleteFailed: 'अनुस्मारक हटाया नहीं जा सका। कृपया पुनः प्रयास करें।',
  reminderPendingSync: 'सिंक की प्रतीक्षा…',
  reminderUpdatePendingSync: 'परिवर्तन सिंक होने की प्रतीक्षा में…',
  queuedReminderNotEditable: 'यह अनुस्मारक सिंक होने की प्रतीक्षा में है। कृपया ऑनलाइन होने के बाद संपादित करें।',
  
  // Appointments
  upcoming: 'आने वाली',
  past: 'पिछली',
  noAppointmentsYet: 'अभी तक कोई नियुक्ति नहीं',
  bookNewAppointment: 'यहाँ सूचीबद्ध देखने के लिए एक नई नियुक्ति बुक करें।',
  loginToSeeAppointments: 'आने वाली मुलाकातें देखने और अपने डॉक्टरों के साथ वीडियो कॉल शुरू करने के लिए लॉगिन करें।',
  myAppointments: 'मेरी नियुक्तियाँ',
  joinCall: 'कॉल में शामिल हों',
  bookNewAppointmentButton: 'नई नियुक्ति बुक करें',
  noScheduleSet: 'कोई शेड्यूल सेट नहीं है',
  meetingLinkNotAvailableAppointment: 'इस नियुक्ति के लिए मीटिंग लिंक उपलब्ध नहीं है।',
  unableToOpenVideoCallAppointment: 'वीडियो कॉल नहीं खोला जा सका। कृपया पुनः प्रयास करें।',
  unableToLoadAppointments: 'इस समय नियुक्तियाँ लोड नहीं की जा सकीं। कृपया बाद में पुनः प्रयास करें।',
  doctor: 'डॉक्टर',
  specialty: 'विशेषता',
  signInToTrackAppointments: 'नियुक्तियों को ट्रैक करने के लिए साइन इन करें',
  
  // Book Appointment
  bookAppointment: 'नियुक्ति बुक करें',
  editAppointment: 'नियुक्ति संपादित करें',
  selectSpecialty: 'विशेषता चुनें',
  selectDate: 'तारीख चुनें',
  selectTime: 'समय चुनें',
  doctorName: 'डॉक्टर का नाम',
  notes: 'नोट्स',
  confirmBooking: 'बुकिंग की पुष्टि करें',
  loadingAppointment: 'नियुक्ति लोड किया जा रहा है...',
  pleaseSignInToBook: 'नियुक्ति बुक करने के लिए कृपया साइन इन करें।',
  pleaseCompleteAllFields: 'कृपया सभी आवश्यक फ़ील्ड भरें।',
  invalidDateOrTime: 'चुनी गई तारीख या समय अमान्य है।',
  chooseFutureTime: 'कृपया अपनी नियुक्ति के लिए भविष्य का समय चुनें।',
  appointmentUpdatedSuccessfully: 'नियुक्ति सफलतापूर्वक अपडेट की गई।',
  appointmentQueued: 'नियुक्ति कतार में जोड़ दी गई है। ऑनलाइन होते ही यह सिंक होगी।',
  appointmentUpdateQueued: 'नियुक्ति अपडेट कतार में है। ऑनलाइन होते ही यह सिंक होगा।',
  couldNotLoadAppointment: 'नियुक्ति लोड नहीं की जा सकी। कृपया बाद में पुनः प्रयास करें।',
  couldNotBookAppointment: 'नियुक्ति बुक नहीं की जा सकी। कृपया पुनः प्रयास करें।',
  appointmentPendingSync: 'सिंक की प्रतीक्षा…',
  appointmentUpdatePendingSync: 'परिवर्तन सिंक होने की प्रतीक्षा में…',
  queuedAppointmentNotEditable: 'यह नियुक्ति सिंक होने की प्रतीक्षा में है। कृपया ऑनलाइन होने के बाद संपादित करें।',
  queuedJoinDisabled: 'यह नियुक्ति सिंक हो जाने के बाद कॉल लिंक उपलब्ध होगा।',
  
  // Booking Confirmed
  bookingConfirmed: 'बुकिंग की पुष्टि हुई',
  bookingConfirmedMessage: 'आपकी नियुक्ति {doctorName} के साथ तय है।',
  assigned: 'नियुक्त',
  pendingSchedule: 'अनुसूचित होने के लिए प्रतीक्षमान',
  joinVideoCall: 'वीडियो कॉल में शामिल हों',
  addToReminder: 'अनुस्मारक में जोड़ें',
  backToAppointments: 'नियुक्तियों पर वापस जाएँ',
  meetingLinkNotAvailable: 'इस नियुक्ति के लिए मीटिंग लिंक उपलब्ध नहीं है।',
  unableToOpenVideoCall: 'वीडियो कॉल नहीं खोला जा सका। कृपया मेरी नियुक्तियों से पुनः प्रयास करें।',
  
  // Document Upload
  uploadOptions: 'अपलोड विकल्प',
  uploadFromGallery: 'गैलरी से अपलोड करें',
  scanOrCapture: 'स्कैन या कैप्चर करें',
  watchVideoToUnderstand: 'वीडियो देखें ताकि समझ सकें कि कैसे अपलोड करें',
  watchVideoMessage: 'यह एक वीडियो प्लेयर खोलेगा जो यूजर को दिखाएगा कि अपने मेडिकल दस्तावेज़ की स्पष्ट फोटो कैसे लें।',
  cameraRollPermissionDenied: 'क्षमा करें, इसके लिए हमें कैमरा रोल की अनुमति की आवश्यकता है!',
  cameraPermissionDenied: 'क्षमा करें, इसके लिए हमें कैमरा की अनुमति की आवश्यकता है!',
  
  // Document Preview
  preview: 'पूर्वावलोकन',
  pleaseSignInToUploadDocs: 'दस्तावेज़ अपलोड करने के लिए कृपया साइन इन करें।',
  documentNotAvailable: 'दस्तावेज़ उपलब्ध नहीं है। कृपया फिर से अपलोड करने का प्रयास करें।',
  pleaseEnterDocumentName: 'कृपया इस दस्तावेज़ के लिए एक नाम दर्ज करें।',
  pleaseConfirmDocumentClear: 'कृपया सुनिश्चित करें कि आपका दस्तावेज़ स्पष्ट और पठनीय है।',
  documentName: 'दस्तावेज़ का नाम',
  addTitleToFindLater: 'बाद में इसे खोजने के लिए एक शीर्षक जोड़ें',
  confirmDocumentUpload: 'दस्तावेज़ अपलोड की पुष्टि करें',
  imageTooLargeAfterCompression: 'संपीड़न के बाद भी छवि बहुत बड़ी है। कृपया एक छोटी छवि चुनें या स्पष्ट क्लोज-अप फोटो लें।',
  imageTooLargeAfterCompression2: 'संपीड़न के बाद भी छवि बहुत बड़ी है। कृपया एक छोटी छवि चुनें।',
  permissionDeniedToUploadDocs: 'आपके पास दस्तावेज़ अपलोड करने की अनुमति नहीं है। कृपया अपने खाते की जांच करें।',
  couldNotUploadDocument: 'दस्तावेज़ अपलोड नहीं किया जा सका। कृपया पुनः प्रयास करें।',
  documentUploadedSuccessfully: 'दस्तावेज़ सफलतापूर्वक अपलोड किया गया!',
  previewNotAvailable: 'पूर्वावलोकन उपलब्ध नहीं है',
  documentUploadQueued: 'दस्तावेज़ कतार में जोड़ दिया गया है। जैसे ही आप ऑनलाइन होंगे यह स्वतः अपलोड हो जाएगा।',
  
  // Documents List
  medicalDocuments: 'चिकित्सा दस्तावेज़',
  uploadDocument: 'दस्तावेज़ अपलोड करें',
  queuedLabel: 'कतार में',
  documentPendingSync: 'अपलोड होने की प्रतीक्षा में…',
  noDocumentsYet: 'अभी तक कोई दस्तावेज़ नहीं',
  uploadPrescriptionsLabReports: 'प्रिस्क्रिप्शन, लैब रिपोर्ट, या डिस्चार्ज सारांश अपलोड करें ताकि वे आसानी से मिल सकें।',
  dateUnavailable: 'तारीख उपलब्ध नहीं है',
  untitledDocument: 'शीर्षक रहित दस्तावेज़',
  pdfViewerNotImplemented: 'PDF दर्शक अभी तक लागू नहीं हुआ। आप अभी भी अपने डिवाइस का उपयोग करके फ़ाइल डाउनलोड कर सकते हैं।',
  documentFormatNotSupported: 'दस्तावेज़ प्रारूप पूर्वावलोकन के लिए अभी तक समर्थित नहीं है।',
  unableToLoadDocuments: 'इस समय दस्तावेज़ लोड नहीं किए जा सके। कृपया बाद में पुनः प्रयास करें।',
  
  // Emergency
  emergencyAlertActive: 'आपातकालीन सतर्कता सक्रिय है',
  alertCancelled: 'सतर्कता रद्द की गई',
  alertingNearestAmbulance: 'निकटतम एम्बुलेंस को सतर्क किया जा रहा है और आपका स्थान भेजा जा रहा है...',
  ambulanceDispatched: 'एम्बुलेंस भेज दिया गया है। बेहतर समन्वय के लिए लाइव मानचित्र दिखाया जा रहा है...',
  emergencyAlertCancelled: 'आपातकालीन सतर्कता रद्द की गई।',
  clickHereToStop: 'रोकने के लिए यहाँ क्लिक करें',
  liveMapTracking: 'लाइव मानचित्र ट्रैकिंग यहाँ दिखाई देगी।',
  locating: 'स्थान निर्धारण किया जा रहा है...',

  // AI Chat Screen
  aiChat: 'AI सहायक',
  aiChatWelcome: 'नमस्ते! मैं आरोग्यमित्र हूँ, आपका स्वास्थ्य साथी। मैं आपके स्वास्थ्य में आपकी सहायता करने के लिए यहाँ हूँ।',
  aiHeroSubtitle: 'लक्षण, डॉक्टर और अनुस्मारक के लिए आपका सर्व-इन-वन स्वास्थ्य साथी',
  aiHeroDescribeSymptoms: 'लक्षणों का वर्णन करें',
  aiHeroBookDoctors: 'डॉक्टर बुक करें',
  aiHeroSetReminders: 'अनुस्मारक सेट करें',
  aiHeroChatNow: 'अभी चैट करें',
  whatCanIHelpYouWith: 'आज आप क्या करना चाहते हैं?',
  notFeelingWell: 'मुझे ठीक महसूस नहीं हो रहा है',
  recordMyVitals: 'मेरे जीवन संकेत रिकॉर्ड करें',
  bookAppointment: 'एक नियुक्ति बुक करें',
  tellMeAboutSymptoms: 'मुझे बताइए कि आप कैसा महसूस कर रहे हैं। कौन सा आपके लिए लागू है?',
  fever: 'मुझे बुखार है',
  cough: 'मुझे खांसी है',
  bodyPain: 'शरीर में दर्द',
  otherSymptom: 'अन्य लक्षण',
  whichVitalToRecord: 'आप कौन सा जीवन संकेत रिकॉर्ड करना चाहते हैं?',
  chooseSpecialty: 'आपको किस प्रकार के डॉक्टर की आवश्यकता है?',
  generalCheckup: 'सामान्य जांच',
  cardiology: 'हृदय विशेषज्ञ',
  neurology: 'मस्तिष्क विशेषज्ञ',
  dermatology: 'त्वचा विशेषज्ञ',
  whatElseCanIHelp: 'मैं और क्या आपकी मदद कर सकता हूँ?',
  backToMenu: 'मेन्यू पर वापस जाएँ',
  continueChat: 'चैट जारी रखें',
  selfCare: 'आत्म-देखभाल सुझाव',
  bookAppointmentForSymptom: 'नियुक्ति बुक करें',
  proceedToRecord: 'रिकॉर्डिंग के लिए आगे बढ़ें',
  proceedToBook: 'बुकिंग के लिए आगे बढ़ें',
  recordingVitalBp: 'शानदार! चलिए आपका रक्तचाप रिकॉर्ड करते हैं।',
  recordingVitalSugar: 'शानदार! चलिए आपकी रक्त शर्करा रिकॉर्ड करते हैं।',
  recordingVitalTemp: 'शानदार! चलिए आपका तापमान रिकॉर्ड करते हैं।',
  recordingVitalHr: 'शानदार! चलिए आपकी हृदय गति रिकॉर्ड करते हैं।',
  bookingWithGeneral: 'मैं आपको एक सामान्य जांच नियुक्ति बुक करने में मदद करूँगा।',
  bookingWithCardio: 'मैं आपको एक हृदय विशेषज्ञ के साथ नियुक्ति बुक करने में मदद करूँगा।',
  bookingWithNeuro: 'मैं आपको एक मस्तिष्क विशेषज्ञ के साथ नियुक्ति बुक करने में मदद करूँगा।',
  bookingWithDerm: 'मैं आपको एक त्वचा विशेषज्ञ के साथ नियुक्ति बुक करने में मदद करूँगा।',
  symptomSelectedFever: 'मैं समझता हूँ आपको बुखार है। क्या आपने अपना तापमान मापा है?',
  symptomSelectedCough: 'मैं समझता हूँ आपको खांसी है। यह कब शुरू हुई?',
  symptomSelectedPain: 'मुझे खेद है कि आप में शरीर का दर्द है। आपके शरीर का कौन सा हिस्सा दर्द करता है?',
  symptomSelectedOther: 'कृपया अपने लक्षणों के बारे में और बताएँ।',
  recommendationForFever: 'बुखार के लिए, खूब पानी पीएँ और अच्छी तरह आराम करें। अगर यह जारी रहे, तो कृपया डॉक्टर को देखें।',
  recommendationForCough: 'खांसी के लिए, शहद या अदरक के साथ गर्म पानी पीएँ। अगर कुछ दिनों में सुधार न हो, तो डॉक्टर से परामर्श लें।',
  recommendationForPain: 'प्रभावित क्षेत्र को आराम दें और गर्म सेक लगाएँ। अगर दर्द बना रहता है, तो कृपया डॉक्टर को देखें।',
  recommendationForOther: 'क्या आप अपने लक्षणों पर डॉक्टर से बात करने के लिए नियुक्ति बुक करना चाहते हैं?',
  errorProcessingRequest: 'क्षमा करें, मुझे समझने में परेशानी हुई। कृपया फिर से प्रयास करें।',
  thinking: 'सोच रहा हूँ...',
  typeMessage: 'एक संदेश लिखें',

  // AI Chat - New Conversational Flow
  describeSymptomsInDetail: 'कृपया अपने लक्षणों के बारे में विस्तार से बताएँ। आप क्या महसूस कर रहे हैं?',
  whichVitalToRecordChat: 'आप कौन सा जीवन संकेत रिकॉर्ड करना चाहते हैं?',
  recordingVitalBP: 'चलिए आपका रक्तचाप रिकॉर्ड करते हैं।',
  recordingVitalSUGAR: 'चलिए आपकी रक्त शर्करा रिकॉर्ड करते हैं।',
  recordingVitalTEMP: 'चलिए आपका तापमान रिकॉर्ड करते हैं।',
  recordingVitalHR: 'चलिए आपकी हृदय गति रिकॉर्ड करते हैं।',
  recordingVitalWEIGHT: 'चलिए आपका वजन रिकॉर्ड करते हैं।',
  proceedToRecordQuestion: 'क्या आप इस माप को रिकॉर्ड करने के लिए तैयार हैं?',
  appointmentQuestion: 'क्या आपके पास पहले से कोई डॉक्टर है, या क्या आप चाहते हैं कि हम कोई सुझाव दें?',
  haveDoctor: 'मेरे पास पहले से डॉक्टर है',
  needSuggestion: 'डॉक्टर सुझाएँ',
  describeProblem: 'कृपया संक्षेप में बताएँ कि आप किस स्वास्थ्य समस्या के बारे में परामर्श लेना चाहते हैं।',
  chooseSpecialtyChat: 'आपकी समस्या के आधार पर, आपको किस प्रकार के विशेषज्ञ की आवश्यकता है?',
  proceedToBookQuestion: 'क्या हम नियुक्ति बुक करने के लिए आगे बढ़ें?',
  seriousSymptomWarning: 'आपके लक्षण गंभीर लग रहे हैं। यदि आपको और बुरा महसूस हो तो कृपया तुरंत किसी क्लिनिक या आपातकालीन केंद्र जाएँ।',
  noDoctorSelected: 'मेरे पास अभी कोई डॉक्टर चयनित नहीं है। कृपया एक बार फिर अपने लक्षण बताएँ।',
  findingSlotWithDoctor: 'बहुत बढ़िया! चलिए {doctorName} के साथ एक स्लॉट ढूंढते हैं। तारीख चुनने के लिए नीचे दिए गए कैलेंडर कार्ड पर टैप करें।',
  reminderType: 'आप किस प्रकार की अनुस्मारक सेट करना चाहते हैं?',
  medicineReminder: 'दवा अनुस्मारक',
  appointmentReminder: 'नियुक्ति अनुस्मारक',
  tabletName: 'कृपया दवा/टैबलेट का नाम बताएँ।',
  tabletDosage: 'आपको कितनी गोलियाँ लेनी हैं?',
  tabletFrequency: 'आपको यह दवा कितनी बार लेनी है? (जैसे, एक बार प्रतिदिन, दिन में दो बार)',
  tabletTime: 'क्या आप चाहते हैं कि मैं आपको याद दिलाने के लिए समय सेट करूँ?',
  doctorName: 'आपके डॉक्टर का नाम क्या है?',
  appointmentDate: 'आपकी नियुक्ति कब है? (जैसे, 15 नवंबर 2024)',
  appointmentTime: 'आपकी नियुक्ति किस समय है? (जैसे, 2:30 PM)',
  reminderSetSuccessfully: 'शानदार! आपकी अनुस्मारक सफलतापूर्वक सेट कर दी गई है।',
  addAnother: 'एक और अनुस्मारक जोड़ें',
  documentUploadQuestion: 'आप मेडिकल डॉक्यूमेंट जैसे प्रिस्क्रिप्शन, लैब रिपोर्ट और डिस्चार्ज सारांश अपलोड कर सकते हैं। क्या आप अभी एक डॉक्यूमेंट अपलोड करना चाहते हैं?',
  medicalDocuments: 'चिकित्सा दस्तावेज़',
  addReminder: 'अनुस्मारक जोड़ें',
  typeYourMessage: 'अपना संदेश लिखें...',
  yes: 'हाँ',
  no: 'नहीं',
  doctorSuggestionPrompt: 'क्या आप इनमें से किसी डॉक्टर का उल्लेख कर रहे थे?',
  reenterName: 'नाम दोबारा दर्ज करें',
  keepDoctorName: '"{doctorName}" नाम ही रखें',
  appointmentDatePrompt: 'अपनी नियुक्ति की तारीख चुनने के लिए नीचे दिए कैलेंडर कार्ड पर टैप करें।',
  continueWithDoctor: 'ठीक है, मैं {doctorName} के साथ आगे बढ़ूँगा।',
  medicineNamePrompt: 'दवा या टैबलेट का नाम क्या है? (यदि आपको नाम नहीं पता, तो बस "मुझे नहीं पता" लिखें। मैं रंग और उपयोग से पहचानने में मदद कर सकता हूँ।)',
  chooseDateFirst: 'कृपया पहले कैलेंडर कार्ड से तारीख चुनें।',
  provideMedicineBeforeReminder: 'रिमाइंडर समय सेट करने से पहले कृपया दवा का नाम और खुराक साझा करें।',
  dateAlreadyPassed: 'यह तारीख निकल चुकी है। कृपया कोई और दिन चुनें।',
  doctorOptionNotFound: 'यह डॉक्टर विकल्प नहीं मिला। कृपया नाम फिर से लिखें।',
  checkingDoctorDirectory: 'एक क्षण दीजिए, मैं इस डॉक्टर को हमारी सूची में देख रहा हूँ...',
  appointmentAlreadyScheduled: 'आपकी नियुक्ति पहले से तय है। कृपया ऊपर दिए बटन से आगे बढ़ें।',
  reminderReady: 'आपका अनुस्मारक तैयार है। कृपया आगे बढ़ने के लिए ऊपर दिए त्वरित बटन का उपयोग करें।',
  doctorSuggestionMissing: 'मैं अभी कोई डॉक्टर सुझाव नहीं दे सका। कृपया अपने लक्षण फिर से बताएँ।',
  doctorSuggestionSummary: 'मैंने उपलब्ध शीर्ष डॉक्टर साझा किए हैं। क्या आप अंतिम डॉक्टर के साथ बुक करना चाहेंगे या अपने लक्षण फिर से बताना चाहेंगे?',
  describeSymptomsPrompt: 'कोई बात नहीं। अपने लक्षण बताएँ, मैं डॉक्टर सुझाऊँगा।',
  symptomDescriptionShortPrompt: 'कृपया अपने लक्षणों के बारे में कुछ शब्द लिखें ताकि मैं मदद कर सकूँ।',
  chooseSpecialtyPrompt: 'मुझे उपयुक्त डॉक्टर नहीं मिला। कृपया आगे बढ़ने के लिए एक विशेषज्ञता चुनें।',
  bookOrAnotherPrompt: 'क्या आप इसी डॉक्टर के साथ बुक करना चाहते हैं या कोई और विकल्प देखना चाहेंगे? आप ऊपर दिए बटन भी उपयोग कर सकते हैं।',
  useCardsHint: 'तारीख या समय चुनने के लिए कृपया ऊपर दिए कार्ड का उपयोग करें या यहाँ लिखें।',
  needAnythingElse: 'क्या आपको और कुछ चाहिए?',
  visitClinicSoon: 'कृपया नज़दीकी क्लिनिक जाएँ या अपने डॉक्टर को कॉल करें। मैं जल्द ही सीधी बुकिंग विकल्प जोड़ूँगा।',
  selfCareOrMenu: 'क्या आप स्व-देखभाल सुझाव फिर से देखना चाहेंगे या मेन्यू पर वापस जाना चाहेंगे?',
  pickNewTime: 'कोई बात नहीं। नया समय चुनने के लिए घड़ी वाले कार्ड का उपयोग करें या यहाँ लिखें।',
  dateAlreadyPassedDetailed: 'यह तारीख निकल चुकी है। कृपया भविष्य की तारीख दर्ज करें (उदाहरण: 15 नव या 15-11-2025)।',
  askAppointmentTime: 'आपकी नियुक्ति का समय क्या है? नीचे दी गई घड़ी का उपयोग करें या समय लिखें (जैसे 10:30 AM या 14:30)।',
  doctorNameNoMatch: 'मुझे कोई नज़दीकी मिलान नहीं मिला। कृपया डॉक्टर का नाम दोबारा लिखें।',
  typeDoctorNameAgain: 'कोई बात नहीं। कृपया डॉक्टर का नाम दोबारा लिखें।',
  askDoctorNameThanks: 'जानकारी के लिए धन्यवाद। डॉक्टर का नाम क्या है?',
  askDoctorNameContinue: 'कृपया डॉक्टर का नाम बताएँ ताकि मैं आगे बढ़ सकूँ।',
  doctorSuggestionSymptomIntro: 'मुझे "{doctorName}" नहीं मिला। {summary} के आधार पर यहाँ कुछ {specialty} डॉक्टर हैं जिन्हें आप चुन सकते हैं:',
  doctorNameFallback: '"{doctorName}" हमारे डॉक्टर सूची में नहीं मिला, लेकिन मैं उसी नाम से बुकिंग जारी रखूँगा।',
  yourConcern: 'आपकी समस्या',
  reenterDatePrompt: 'कृपया तारीख फिर से दर्ज करें। आप ऐसे प्रारूप का उपयोग कर सकते हैं:\n• 15 नव\n• 15-11-2025\n• नव 15\n• नवम्बर 15, 2025',
  needDateBeforeTime: 'समय तय करने से पहले मुझे नियुक्ति की तारीख चाहिए। कृपया तारीख फिर से साझा करें।',
  reenterAppointmentTime: 'कृपया घड़ी कार्ड का उपयोग करके या टाइप करके नियुक्ति का समय फिर से चुनें।',
  apiKeyMissing: 'Gemini API कुंजी उपलब्ध नहीं है। कृपया app.json > extra.geminiApiKey में इसे कॉन्फ़िगर करें।',
  selfCarePlanOrDoctor: 'क्या आप स्व-देखभाल योजना चाहते हैं या किसी डॉक्टर से संपर्क करना चाहेंगे?',
  symptomNetworkIssue: 'मुझे समस्या आई। कृपया अपना इंटरनेट कनेक्शन जांचें और अपने लक्षण फिर से बताने का प्रयास करें।',
  tabletColorPrompt: 'कोई बात नहीं! मैं मदद करता हूँ। टैबलेट का रंग क्या है? (जैसे सफेद, लाल, नीला, पीला आदि)',
  medicineNameClarification: 'मुझे समझ नहीं आया। कृपया दवा का नाम बताएं या बताएं कि आपको नाम नहीं पता।',
  tabletPurposePrompt: 'अच्छा! अब बताएं, यह दवा किस लिए है? (जैसे दिल, रक्तचाप, सिरदर्द, बुखार आदि)',
  tabletColorClarification: 'कृपया रंग का वर्णन करें। जैसे सफेद, लाल, नीला, पीला, हरा, नारंगी, गुलाबी, भूरा, काला आदि?',
  tabletUsageClarification: 'यह दवा किस काम की है? (जैसे रक्तचाप, दर्द, दिल, मधुमेह, बुखार आदि)',
  tabletReminderTimePrompt: 'मैं आपको किस समय याद दिलाऊँ? नीचे दिए घड़ी कार्ड का उपयोग करके सटीक समय चुनें।',
  estimateDosagePrompt: 'कोई बात नहीं! क्या आप अनुमान बता सकते हैं? जैसे "1 टैबलेट", "आधा टैबलेट" या "2 टैबलेट"?',
  dosageClarificationPrompt: 'मुझे खुराक समझ नहीं आई। कृपया "1 टैबलेट", "आधा", "2 टैबलेट" जैसी जानकारी दें।',
  medicineTimeParseHint: 'मुझे "{userInput}" समझ नहीं आया। कृपया ऊपर दिए घड़ी कार्ड पर टैप करें या समय इस तरह दर्ज करें:\n• 14:30 (24-घंटे)\n• 2:30 PM (12-घंटे)\n• 14 30 (स्पेस के साथ)\n• 2 30 pm (स्पेस के साथ)',
  dateParseHint: 'मुझे "{userInput}" समझ नहीं आया। कृपया तारीख इस तरह लिखें:\n• 15 नव\n• 15-11-2025\n• नव 15\n• नवम्बर 15, 2025',
  timeParseHint: 'मुझे "{userInput}" समझ नहीं आया। आप ऊपर घड़ी पर टैप कर सकते हैं या समय इस तरह दर्ज करें:\n• 14:30 (24-घंटे)\n• 2:30 PM (12-घंटे)\n• 14 30 (स्पेस के साथ)\n• 2 30 pm (स्पेस के साथ)',
  clockPickerSubtitleDefault: 'अपना पसंदीदा घंटा और मिनट चुनें।',
  pickReminderTimeTitle: 'रिमाइंडर समय चुनें',
  reminderTimeSubtitle: 'एक घंटा और फिर एक मिनट चुनें। याद दिलाना रोज़ इसी समय होगा।',
  bookAnotherAppointment: 'एक और नियुक्ति बुक करें',
  confirmParsedTime: 'क्या आपका मतलब {value} था? क्या यह सही है?',
  reviewAttachedImage: 'कृपया संलग्न चित्र देखें।',
  genericDoctorName: 'डॉक्टर',
  acceptingNewPatients: 'नए मरीज स्वीकार किए जा रहे हैं',
  currentlyWaitlisted: 'फिलहाल प्रतीक्षा सूची में (मैं स्लॉट का अनुरोध कर सकता हूँ)',
  symptomUnderstanding: 'मैंने यह समझा: {summary}',
  thanksForDetails: 'जानकारी साझा करने के लिए धन्यवाद!',
  bestSpecialtyFit: 'इसके आधार पर, {specialty} सबसे उपयुक्त होगा।',
  doctorExperienceLabel: 'अनुभव: {years}+ वर्ष',
  doctorLanguagesLabel: 'भाषाएँ: {languages}',
  doctorStatusLabel: 'स्थिति: {status}',
  bookWithThisDoctor: 'इसी डॉक्टर के साथ बुक करें',
  showAnotherDoctor: 'कोई और डॉक्टर दिखाएँ',
  bookPreviousDoctor: 'पिछले डॉक्टर को बुक करें',
  describeSymptomsAgain: 'लक्षण फिर से बताएँ',
  medicineReminderConfirmation: 'शानदार! मैंने {medicineName} के लिए {time} बजे का दैनिक रिमाइंडर सेट किया है। आपको हर दिन इसी समय याद दिलाया जाएगा।',
  appointmentReminderConfirmation: 'ठीक है! मैंने {doctorName} के साथ {date} को {time} बजे की नियुक्ति का रिमाइंडर सेट कर दिया है और उसे "मेरी नियुक्तियाँ" टैब में जोड़ दिया है।',
  escalateToDoctor: 'डॉक्टर से संपर्क करें',
  selfCarePlan: 'स्व-देखभाल योजना',
  selfCarePlanIntro: 'यहाँ एक सरल स्व-देखभाल योजना है:',
  selfCareTip1: 'यदि डॉक्टर ने मना न किया हो तो दिन में 8-10 गिलास पानी पिएँ।',
  selfCareTip2: 'खिचड़ी या सूप जैसी हल्की, घर की बनी चीजें खाएँ।',
  selfCareTip3: '7-8 घंटे सोएँ और स्क्रीन पर कम समय बिताएँ।',
  selfCareTip4: 'खुद से नई दवा न लें; सिर्फ पहले से बताई दवाएँ ही लें।',
  selfCareTip5: 'अगर लक्षण बढ़ें या नए लक्षण आएँ तो तुरंत डॉक्टर से संपर्क करें।',
  
  // Medical Documents Chat
  takingToUploadScreen: 'अब मैं आपको अपने मेडिकल दस्तावेज़ को अपलोड करने के लिए ले जा रहा हूँ...',
  continueToUpload: 'अपलोड करने के लिए जारी रखें',
  documentUploadSkipped: 'कोई समस्या नहीं! आप कभी भी मेडिकल दस्तावेज़ अपलोड कर सकते हैं। बस मेडिकल दस्तावेज़ सेक्शन पर जाएं।',
  
  // AI Chat - Vital Recording Instructions
  bpInstructions: 'आपके रक्तचाप को रिकॉर्ड करने के लिए, आपको एक रक्तचाप मशीन (डिजिटल या मैनुअल) की आवश्यकता होगी। कृपया अपना रक्तचाप मापें और दो रीडिंग दें: सिस्टोलिक (ऊपरी संख्या) और डायास्टोलिक (निचली संख्या)। उदाहरण के लिए: 120 80 या 120/80। कृपया अपनी रीडिंग दर्ज करें।',
  sugarInstructions: 'आपकी रक्त शर्करा को रिकॉर्ड करने के लिए, आपको एक ग्लूकोज मीटर की आवश्यकता होगी। कृपया अपनी उंगली को धीरे से चुभोएं और मीटर का उपयोग करके अपनी रक्त शर्करा को मापें। रीडिंग को mg/dL में दर्ज करें। उदाहरण के लिए: 120। कृपया अपनी रीडिंग दर्ज करें।',
  tempInstructions: 'आपके तापमान को रिकॉर्ड करने के लिए, आपको एक थर्मामीटर (डिजिटल, इन्फ्रारेड, या पारे का) की आवश्यकता होगी। इसे अपनी बांह के नीचे या मुंह में रखें और अपने शरीर का तापमान मापें। रीडिंग को फ़ारेनहाइट में दर्ज करें। उदाहरण के लिए: 98.6। कृपया अपनी रीडिंग दर्ज करें।',
  hrInstructions: 'आपकी दिल की गति को रिकॉर्ड करने के लिए, आप अपनी नाड़ी को मैनुअली गिन सकते हैं या एक डिवाइस का उपयोग कर सकते हैं। एक पूरी मिनट के लिए अपनी नाड़ी लें। अपनी हृदय गति को beats per minute (bpm) में दर्ज करें। उदाहरण के लिए: 72। कृपया अपनी रीडिंग दर्ज करें।',
  weightInstructions: 'अपना वजन रिकॉर्ड करने के लिए, कृपया सुबह नाश्ते से पहले एक वजन मापने वाली मशीन पर खड़े हों। अपना वजन किलोग्राम में दर्ज करें। उदाहरण के लिए: 70। कृपया अपनी रीडिंग दर्ज करें।',
  spo2Instructions: 'अपना SpO2 (ऑक्सीजन संतृप्ति) रिकॉर्ड करने के लिए, आपको एक पल्स ऑक्सीमीटर की आवश्यकता होगी। इसे अपनी उंगली पर रखें और रीडिंग की प्रतीक्षा करें। अपने SpO2 प्रतिशत को दर्ज करें। उदाहरण के लिए: 98। कृपया अपनी रीडिंग दर्ज करें।',
  
  // Vital validation error messages
  bpFormatError: 'कृपया रक्तचाप के लिए दो रीडिंग दें (सिस्टोलिक और डायास्टोलिक)। प्रारूप का उपयोग करें: 120 80 या 120/80',
  bpRangeError: 'रक्तचाप के मान सामान्य सीमा से बाहर लगते हैं। सामान्य सीमा: सिस्टोलिक 60-250, डायास्टोलिक 30-150। कृपया जांचें और फिर से प्रयास करें।',
  sugarFormatError: 'कृपया एक ही रक्त शर्करा रीडिंग दर्ज करें। प्रारूप का उपयोग करें: 120',
  sugarRangeError: 'रक्त शर्करा का मान सामान्य सीमा से बाहर लगता है। सामान्य सीमा: 50-500 mg/dL। कृपया जांचें और फिर से प्रयास करें।',
  tempFormatError: 'कृपया एक ही तापमान रीडिंग दर्ज करें। प्रारूप का उपयोग करें: 98.6',
  tempRangeError: 'तापमान का मान सामान्य सीमा से बाहर लगता है। सामान्य सीमा: 95-105°F। कृपया जांचें और फिर से प्रयास करें।',
  hrFormatError: 'कृपया एक ही दिल की गति की रीडिंग दर्ज करें। प्रारूप का उपयोग करें: 72',
  hrRangeError: 'दिल की गति का मान सामान्य सीमा से बाहर लगता है। सामान्य सीमा: 40-200 bpm। कृपया जांचें और फिर से प्रयास करें।',
  weightFormatError: 'कृपया एक ही वजन की रीडिंग दर्ज करें। प्रारूप का उपयोग करें: 70',
  weightRangeError: 'वजन का मान सामान्य सीमा से बाहर लगता है। सामान्य सीमा: 10-250 kg। कृपया जांचें और फिर से प्रयास करें।',
  spo2FormatError: 'कृपया एक ही SpO2 रीडिंग दर्ज करें। प्रारूप का उपयोग करें: 98',
  spo2RangeError: 'SpO2 का मान सामान्य सीमा से बाहर लगता है। सामान्य सीमा: 70-100%। कृपया जांचें और फिर से प्रयास करें।',
  vitalSavedSuccessfully: 'शानदार! आपकी रीडिंग सफलतापूर्वक रिकॉर्ड की गई है।',
  recordAnother: 'एक और रिकॉर्ड करें',
  tryAgain: 'फिर से प्रयास करें',
  errorSavingVital: 'आपकी महत्वपूर्ण रीडिंग को सहेजने में त्रुटि हुई। कृपया फिर से प्रयास करें।',
};

export default hi;
